export const STUDY_NOTES_ENABLED = false;
export const STUDY_ANKI_ENABLED = false;
export const STUDY_FOCUS_ENABLED = false;
export const STUDY_PROGRESS_ENABLED = false;
export const STUDY_ACHIEVEMENTS_ENABLED = false;

export const STUDY_MAINTENANCE_NOTICE = !STUDY_FOCUS_ENABLED
  || !STUDY_PROGRESS_ENABLED
  || !STUDY_ACHIEVEMENTS_ENABLED
  || !STUDY_NOTES_ENABLED;
